### ISSUE TITLE
There is an error in the git command and explanation

### ISSUE THREAD

**Issue by MarkBTomlinson** [nicksp/dotfiles#1]
the command shown is
`git clone https://github.com/nicksp/dotfiles.git ~/.dotfiles`

where it should be ?
`git clone https://github.com/nicksp/dotfiles.git ~/dotfiles`

As the given command creates a different directory from the one expected also the subsequent command for curl also have `.dotfiles`

**Comment by nicksp** [comment]
Good catch @MarkBTomlinson 
Reflected these changes in [README.md](https://github.com/nicksp/dotfiles/blob/master/README.md)
