### ISSUE TITLE
Unistall

### ISSUE THREAD

**Issue by asaduzzaman-shuvro** [nicksp/dotfiles#7]
How can uninstall the them?

**Comment by Razpudding** [comment]
I'd also like to know this. The install didn't completely work for me. It still loads up bash and when I switch to zsh I get a lot of weird output and my cli changes to `\[\033]0;\w\007\]\[\]\n\[\]\u\[\] at \[\]\h\[\] in \[\]\w$(prompt_git " on ")\n\[\]$ \[\]`

So what's the best way to revert back to my old setting? Just delete the dotfiles folder and move back the stuff from dotfiles_old?
